version: "3.8"

services:
  db:
    container_name: vantage6-rdb
    image: postgres:12.6
    environment:
      POSTGRES_DB: ServerDB
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      OMOP_CDM: ${OMOP_CDM}
    volumes:
      - $PWD/db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - $PWD/db/data:/mnt/data
    networks:
      - vantage6_server

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - vantage6_server

  server:
    container_name: vantage6_server
    image: harbor.vantage6.ai/infrastructure/server:2.1.1
    ports:
      - 5000:5000
    environment:
      - PROXY_SERVER_PORT=80
      - PGUSER=postgres
      - PGPASSWORD=${POSTGRES_PASSWORD:-password}
      - PGDATABASE=ServerDB
      - PGPORT=5432
      - PGHOST=db
    volumes:
      - $PWD/server/config/config.yaml:/config.yaml
      - $PWD/server/config/init.yaml:/init.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["vserver-local", "start", "-c", "/config.yaml", "-e", "prod"]
    networks:
      - vantage6_server
    restart: unless-stopped
    depends_on:
     - db

  maastro-user:
    container_name: vantage6-maastro-user
    image: harbor.distributedlearning.ai/infrastructure/node:2.1.0
    #image: pmateus/vantage6-node-whitelisted:1.0.0
    environment:
      - DATA_VOLUME_NAME=datavol-maastro
    volumes:
      - datavol-maastro:/mnt/data
      - $PWD/maastro/log:/mnt/log
      - $PWD/maastro/config:/mnt/config
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["vnode-local", "start", "-c", "/mnt/config/maastro.yaml", "--dockerized"]
    networks:
      - vantage6_server
    depends_on: 
      - server
    restart: unless-stopped

  mumc-user:
    container_name: vantage6-mumc-user
    image: harbor.distributedlearning.ai/infrastructure/node:2.1.0
    #image: pmateus/vantage6-node-whitelisted:1.0.0
    environment:
      - DATA_VOLUME_NAME=datavol-mumc
    volumes:
      - datavol-mumc:/mnt/data
      - $PWD/mumc/log:/mnt/log
      - $PWD/mumc/config:/mnt/config
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["vnode-local", "start", "-c", "/mnt/config/mumc.yaml", "--dockerized"]
    networks:
      - vantage6_server
    depends_on: 
      - server
    restart: unless-stopped

volumes:
  datavol-maastro:
    external: true
  datavol-mumc:
    external: true

networks:
  vantage6_server:
    name: vantage6_server
