organizations:
  -
    name: "MAASTRO Clinic"
    domain: "maastro.nl"
    address1: "Dr. Tanslaan 12"
    address2: "Maastricht"
    zipcode: "6229ET"
    country: "Netherlands"
    public_key: ""
    users:
      -
        username: "researcher"
        firstname: "Researcher"
        lastname: "van Maastro"
        email: "researcher@maastro.nl"
        roles: []
        password: "password"
  -
    name: "Maastricht University Medical Center"
    domain: "mumc.nl"
    address1: "Dr. Tanslaan 12"
    address2: "Maastricht"
    zipcode: "6229ET"
    country: "Netherlands"
    public_key: ""
  -
    name: "University of Minho"
    domain: "um.pt"
    address1: "UM"
    address2: "Braga"
    zipcode: "4700"
    country: "Portugal"
    public_key: ""

collaborations:
  -
    name: "demo-maastro-mumc"
    encrypted: false
    participants:
      -
        name: "MAASTRO Clinic"
        api-key: "2bb02b20-d035-11ea-9365-0242ac110002"
      -
        name: "Maastricht University Medical Center"
        api-key: "414a303e-d035-11ea-9365-0242ac110002"
      -
        name: "University of Minho"
        api-key: "7f77bdff-1045-470b-af6b-36d418ae445c"
